### ISSUE TITLE
非常方便，几点建议希望能考虑

### ISSUE THREAD

**Issue by CuteLicense** [ZX-11/edgetts-cli#1]
1. 段落中包含 & 符号时无法转换，建议加上相应处理；
2. 建议参数能增加指定段落进行转换，方便解决转换失败段落修改调整后重新转换的问题；
3. 对转换失败的段落能否考虑加上重试次数限制？并且在结束后给出具体失败的段落信息；
4. 对于 书名txt.parts 里面 webm 文件，能否增加单独的合并/转换命令

**Comment by ZX-11** [comment]
1. 这个可能是微软接口的限制，可以手动去除，或自行修改代码批量删除符号
2-4. 正在测试新版本稍后发布，将所有音频段落统一存储，并软链接到单独的目录，这样修改单独的段落后，未修改的段落可以复用
